### PR TITLE
Wip service setup

### PR DESCRIPTION
**Pull request by amindadgar**

### CODE REVIEW

**Comment by amindadgar** [comment]
GitHub secrets required:
-  `GITHUB_TOKEN`
- `CC_TEST_REPORTER_ID`

**Comment by amindadgar** [comment]
> `CC_TEST_REPORTER` was added.
> 
> The idea is to move away from DAOlytics so why are we using `GITHUB_TOKEN`?

Thanks for the response. Basically, this repository is discord-analyzer-service which uses the discod-analyzer (more specifically `rndao_analyzer`) library to set up the discord analytics workflow and listen to events. I was going to ask to change this repository name to something like `discord-analyzer-service` as its job is to run our discord analyzer library codes.

So basically, since we're using the `rndao_analyzer` library we still have to use DAOlytics repository since our library is there. If we're going to have the rndao_analyzer library somewhere else than DAOlytics we have another migration to do and then we won't need the `GITHUB_TOKEN`.

**Comment by amindadgar** [comment]
> Our goal should be to move away from DAOlytics. This is due to the fact that
> 
> 1. DAOlytics is used as a playground for a bunch of different research
> 2. DAOlytics isn't build as a production library
> 
> So ultimately: The code that is today in DAOlytics that is used for analysis should be move to:
> 
> 1. a library used across multiple platforms i.e. `core-lib-py`
> 2. into the respective analyzer service i.e. `discord-analyzer`, `twitter-analyzer`, etc.

So until now what we've done is this
- [x] a library used across multiple platforms i.e. `core-lib-py` (some naming conventions is tbd)
- [ ] into the respective analyzer service i.e. `discord-analyzer`, `twitter-analyzer`, etc.

For the second item, my here's my opinion copied from discord
> In this case, the library won't be a library anymore and we would need to clone the code and run the project (?), since we need at least a script to run for example the server and worker. What do you think about this? ( I'm not sure whether cloning the whole code is a good practice or not)

**Comment by amindadgar** [comment]
Ok, so in this case, I have to import more code from DAOlytics into this repository to make up the `discord-analyzer` and to remove the dependency to clone DAOlytics using the `GITHUB_TOKEN` And this would be still a work-in-progress.

**Review by TjitsevdM — APPROVED** [review]

**Pull request merged**
